server:
  port: 9980
catman:
  recognition:
    mineru-endpoint: http://localhost:8000
  file:
    mode: minio
    minio:
      endpoint: http://localhost:9001
      accessKey: minioadmin
      secretKey: minioadmin
      bucketName: catman
    local:
      path: /home/catman
  datasource:
    url: jdbc:postgresql://192.168.1.88:5555/rag_test
    username: pgvector
    password: pgvector
    driver-class-name: org.postgresql.Driver
    connection-timeout: 30000
    maximum-pool-size: 10
    minimum-idle: 10
    idle-timeout: 600000