server:
  port: 9988
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
catman:
  file:
    mode: local
    minio:
      endpoint: http://localhost:9001
      accessKey: minioadmin
      secretKey: minioadmin
      bucketName: catman
    local:
      path: /home/catman
  datasource:
    url: jdbc:postgresql://192.168.1.88:5555/rag_test
    username: pgvector
    password: pgvector
    driver-class-name: org.postgresql.Driver
    connection-timeout: 30000
    maximum-pool-size: 10
    minimum-idle: 10
    idle-timeout: 600000
  toolcall:
    mcp:
      tavily:
        key: @tavily.key@
        url: https://mcp.tavily.com/mcp/
  recognition:
    mineru-endpoint: http://localhost:8000
spring:
  main:
    web-application-type: servlet
  ai:
    openai:
      api-key: @api.key@
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          max-tokens: 4096
          temperature: 0.7
          model: qwen-plus